### ISSUE TITLE
xps 15 9560 Mac os Mojave 10.14.3  安装问题求助

### ISSUE THREAD

**Issue by BillTaozi** [daliansky/Hackintosh#1]
制作了安装U盘，安装启动卡在了下面如图所示
![wechatimg3](https://user-images.githubusercontent.com/35515198/53630951-4be52400-3c4c-11e9-999e-b3179fa69a3d.jpeg)

**Comment by daliansky** [comment]
请通过QQ群寻求帮助，详见博客文章下方的QQ群列表
