### ISSUE TITLE
提交一个零刻Turbo5   90%完美EFI

### ISSUE THREAD

**Issue by bbcclove** [daliansky/Hackintosh#104]
配置：CPU：i5-8305G
         主板：intel HM175
         内存：16G DDR4 2666
         显卡 ：UHD630+AMD Radeon Vega M GL 4G HBM2显存
         硬盘：1.5T SSD 光威悍将SATA
         显示器：15.6寸 4K 触摸屏
1、USB接口定制，现在5个USB口均可正常识别
2、集显、独显均已驱动，核显加速正常
3、内存识别2400，不是2666，应该是内存的问题
4、没有测试DP输出是否正常。
5、声卡现在有显示内建声卡和麦克风，不过没有测试
6、触摸屏无解，插上去只能识别一个USB集线器，设备号也能识别，就是没法使用
7、网卡因为原来手上剩了一个BCM94360HMB的PCIE网卡，所以这次使用转接卡用的这个mini pcie无线网卡，蓝牙、无线均可正常识别
8、CPU变频不知道怎么回事，用CPU-S检测始终都是未睿频、没有变频档位，但是使用Intel Power Gadget检测好像又有
9、望大神帮忙看看触摸屏有无可能驱动，我记得原来我的话说N550触摸屏的笔记本是原生驱动的，但是这个单独的显示器没办法，不知道怎么驱动，谢谢（附上我的原始origin）

[EFI-CLOVER.zip](https://github.com/daliansky/Hackintosh/files/3894873/EFI-CLOVER.zip)

[origin.zip](https://github.com/daliansky/Hackintosh/files/3894878/origin.zip)

**Comment by sillydu** [comment]
上个月看到冥王峡谷驱动了，就在想这台机器。纠结要不要买。
