### ISSUE TITLE
i7-10710u

### ISSUE THREAD

**Issue by acoutts** [daliansky/Hackintosh#126]
Hi - is there any success yet on a 10th gen i7?

Am trying to get Lenovo X1C7 to boot (6 core i7-10710u) but no luck so far.

My clover / OC:
https://github.com/acoutts/x1c7-hackintosh

**Comment by daliansky** [comment]
https://github.com/daliansky/XiaoXinPro-13-2019-hackintosh
![81XB](http://7.daliansky.net/DW1820A/81XB.jpg)

**Comment by osxtremez** [comment]
Hello,
I'm also trying to install Mojave on i7-10710U (Dell XPS13-7390.
Followed you link above but was not successful.
here's the screenshot.
pls advise.
TIA.
![11334102168859](https://user-images.githubusercontent.com/60092853/73260962-a6d91f80-41fd-11ea-84c0-31b0310bcf0e.jpg)

**Comment by evgenyrud** [comment]
Are there good new with i7-10710u?
Created Clover EFS but not able to boot Catalina USB. Stuck from the very beginning.

**Comment by astrocycles** [comment]
Hi,
I'm new to this.
Should the CPU be exactly the same as above or this could work with NUC 10 for example ? 
many thanks

**Comment by 1alessandro1** [comment]
Hi, any success with IceLake? Particularly with Lenovo IceLake laptops?

**Comment by Ali-Jamali** [comment]
> Hi, any success with IceLake? Particularly with Lenovo IceLake laptops?

I try it in 10.15.5 with clover and OC 
Both not booting

**Comment by griffins** [comment]
i managed to boot on open core, the camera is working, Bluetooth, keyboard, slight issues with the touchpad,   am supposed to replace the wifi card but am yet, i have no igpu acceleration yet.

**Comment by griffins** [comment]
Touch Pad was fixed.  My IGPU isnt for ice lake but some sort of comet lake, device id 0x9b41, i believe some 630 UHD graphics should work,

**Comment by RotatingFans** [comment]
@griffins Is that with the 10710?

**Comment by griffins** [comment]
yep!

**Comment by RotatingFans** [comment]
Be sure to keep us updated! It seems you may be one of the first.

**Comment by griffins** [comment]
i will

**Comment by LEXUGE** [comment]
> i managed to boot on open core, the camera is working, Bluetooth, keyboard, slight issues with the touchpad, am supposed to replace the wifi card but am yet, i have no igpu acceleration yet.
> 
> its a Dell XPS13-7390
> PS, i swapped the nvme to a samsung evo pro.

Would you like to upload your EFI to a GitHub repo?

**Comment by griffins** [comment]
https://github.com/griffins/dell-xps-7390

Any help to sort the GPU acceleration is appreciated.

**Comment by griffins** [comment]
according to this we have a uhd 620 comet lake version 
https://www.notebookcheck.net/Intel-Core-i7-10510U-Laptop-Processor-Comet-Lake-U.430586.0.html

**Comment by griffins** [comment]
faking the device id gets GPU acceleration but it get stuck at the ioconsoleusers gioscreenlockstate 3 just before login screen. so its a graphics issue. the only way to boot is to use a none-existent device id and let the os fall back to using builtin graphics.

**Comment by macblizzard** [comment]
> faking the device id gets GPU acceleration but it get stuck at the ioconsoleusers gioscreenlockstate 3 just before login screen. so its a graphics issue. the only way to boot is to use a none-existent device id and let the os fall back to using builtin graphics.

to which older version did you fake it to? did you follow any guide to fake it?
