### ISSUE TITLE
OpenCore EFI for MSI MPG X570 Gaming Plus

### ISSUE THREAD

**Issue by yhl452493373** [daliansky/Hackintosh#130]
适用于MSI MPG X570 Gaming Plus的OpenCore引导，支持MacOS 10.15.2,DW 1560A应该是驱动了的。

哪个老哥有空帮我填个链接。。不想编辑这个MD了，太长了。。。。

EFI地址
[https://github.com/yhl452493373/OpenCore-EFI-for-MSI-MPG-X570-Gaming-Plus](https://github.com/yhl452493373/OpenCore-EFI-for-MSI-MPG-X570-Gaming-Plus)

**Comment by yhl452493373** [comment]
USB端口是定制的，不然USB识别不完，其他机型需要自行定制USB，机型为iMacPro1,1，USBPower中也是改机型为iMacPro1,1，如果不用这个机型，需要Config.plist和USBPower一起改。

**Comment by SuperY** [comment]
@yhl452493373  那个仓库的配置， USB2正常么？我USB3正常，但是usb2没法使用。
导致蓝牙无法识别。
