### ISSUE TITLE
dell 5560 EFI和CLOVER

### ISSUE THREAD

**Issue by luoxulx** [daliansky/Hackintosh#133]
![阿里旺旺图片20200111220002](https://user-images.githubusercontent.com/35016570/72813242-fa97b600-3c9d-11ea-897b-ed5643e67678.jpg)
折腾了两个星期了，我的电脑真的不能黑苹果吗。。。求大佬支招

**Comment by zdx8910** [comment]
I have an EFI suit this device
But it's too big to attached in comment

**Comment by luoxulx** [comment]
really？luoxulx@aliyun.com，Thanks

发自我的iPhone

在 2020年4月5日，11:41，zdx8910 <notifications@github.com> 写道：

﻿

I have an EFI suit this device
But it's too big to attached in comment
