### ISSUE TITLE
华硕 STRIX B250G GAMING i7 7700 GTX1060+EFI

### ISSUE THREAD

**Issue by QLYong829** [daliansky/Hackintosh#164]
![微信截图_20200403085009](https://user-images.githubusercontent.com/63031271/78313073-444b2980-7588-11ea-9a5e-e46f0a859ee0.png)

**Comment by LANRRI** [comment]
华硕b150主板，i76700 u， n1070ti显卡。系统卡顿，webdriver已装，显卡也能识别，老哥的efi找到了吗？求助

**Comment by speji** [comment]
你从这里面找找有没有你的 我是用的万能通用里面的
链接：https://pan.baidu.com/s/1aAyXqGj9f9kpzwiBUN1ppw 
提取码：6vl2


在2020年6月22日 23:15，李瑞端<notifications@github.com> 写道：

华硕b150主板，i76700 u， n1070ti显卡。系统卡顿，webdriver已装，显卡也能识别，老哥的efi找到了吗？求助

**Comment by LANRRI** [comment]
感谢大佬，我试试
