### ISSUE TITLE
MagicBookPro-16这个已经变收费的项目了，建议移除

### ISSUE THREAD

**Issue by sursamer** [daliansky/Hackintosh#185]

**Comment by y010204025** [comment]
收不收费是个人的选择，一个愿打，一个愿挨，我们没必要去干预。
只要吃相不要太难看就行，免费的会存在，收费的也会存在。如果认同，请关闭这个issue。不认同请继续回复。

**Comment by y010204025** [comment]
收不收费是个人的选择，一个愿打，一个愿挨，我们没必要去干预。
只要吃相不要太难看就行，免费的会存在，收费的也会存在。如果认同，请关闭这个issue。不认同请继续回复。

**Comment by kongbg** [comment]
什么叫一个愿打，一个愿挨？
上面也有收录了我开源的配置，开源出来的能拿来收费？
你懂什么叫开源吗？

**Comment by wklxd** [comment]
支持开源，也不反对收费，相对于初学者自己配置EFI，有人能够把经过测试的EFI提供出来，即使收费也可以理解。作者仅是做一个索引，让大家能够有渠道很容易的找到希望的EFI，是否收费不是作者关心的问题

**Comment by daliansky** [comment]
> 什么叫一个愿打，一个愿挨？
> 上面也有收录了我开源的配置，开源出来的能拿来收费？
> 你懂什么叫开源吗？

开源的好处是：方便小白直接套用，同时也方便`淘宝奸商`拿着开源的EFI进行付费安装。
