### ISSUE TITLE
目前是否有机型推荐？

### ISSUE THREAD

**Issue by kidd808** [daliansky/Hackintosh#189]
hi,

我现在打算购买笔记本，是否有笔记本的推荐？

我以为得有很多人问这种问题，结果竟然没有找到。

不想回答也没关系。辛苦了

**Comment by Jetcser** [comment]
笔记本应该不好装黑苹果吧，而且既然喜欢苹果的话，直接买macbook就好一些，而且现在一般笔记本的价格都快赶上macbook了。



可用于iOS的myMail发送


2020年6月1日 星期一 +0800 上午10:19 发件人 notifications@github.com  <notifications@github.com>:

**Comment by shadow-rt** [comment]
I think lenovo xiaoxin pro13(with intel cpu) may be a good choice. 2k display screen is vital to hacintosh.

**Comment by daliansky** [comment]
笔记本就目前来讲，我个人也推荐使用联想小新Pro

**Comment by kidd808** [comment]
> 笔记本就目前来讲，我个人也推荐使用联想小新Pro

y9000x 怎么样？我目前在关注这个。已经准备出手了

**Comment by kidd808** [comment]
> I think lenovo xiaoxin pro13(with intel cpu) may be a good choice. 2k display screen is vital to hacintosh.

how about y9000x?

**Comment by wklxd** [comment]
Y9000X也是一个好机，做工性能啥的，都ok，除了喇叭外放没有声音，15寸，看大小是否合你的意

**Comment by wklxd** [comment]
预算有限可以考虑 DELL 5488，也是一个性价比相当高的机器，换原装网卡后，基本完美
