### ISSUE TITLE
跪求技嘉b460m  AORUS PRO+10400+蓝宝石5600xt的efi

### ISSUE THREAD

**Issue by Lance-93** [daliansky/Hackintosh#208]

**Comment by ashunblog** [comment]
挖~老兄你的配置跟我完全一樣啊!卡一個

**Comment by ashunblog** [comment]
大部分驅動ok 
[https://drive.google.com/file/d/1f_G5MNtewbyEoPFNJla1mq7i9sOmTaYu/view?usp=sharing](https://drive.google.com/file/d/1f_G5MNtewbyEoPFNJla1mq7i9sOmTaYu/view?usp=sharing)

**Comment by Lance-93** [comment]
先感谢了！
