### ISSUE TITLE
Thinkpad P50

### ISSUE THREAD

**Issue by Errrneist** [daliansky/Hackintosh#25]
我之前做了个P50的有点老 但是可以收录一下 好像还没人做
https://github.com/Errrneist/Hackintosh-Thinkpad-P50

**Comment by daliansky** [comment]
> 我之前做了个P50的有点老 但是可以收录一下 好像还没人做
> https://github.com/Errrneist/Hackintosh-Thinkpad-P50

能更新下吗，10.12可能没几个人用了。如果更新后请通知我收录。

**Comment by Errrneist** [comment]
我一年半前就卖掉了，于是就不更新了。
