### ISSUE TITLE
大神，Dell 9020mt可以支持nvme SSD吗？EFI里面是否可以从别的EFI拷贝nvme驱动来支持？

### ISSUE THREAD

**Issue by learningendless** [daliansky/Hackintosh#30]
大神，Dell 9020m可以支持nvme SSD吗？EFI里面是否可以从别的EFI拷贝nvme驱动来支持？我看目前efi的driver里面是没有nvme的efi驱动，是不是可以从别的efi里拷贝一个过来来支持nvme？想要买个nvme的ssd，通过pcie转nvme板卡来插一个M.2接口的nvme协议的SSD来提升性能，不知道是否可行？（总的来说，不升级bios，在机械硬盘里分出一个efi分区，bios引导这个efi，这个efi里如果有nvme的efi驱动的话，可以从nvme SSD启动macos）

**Comment by daliansky** [comment]
如果主板支持nvme那肯定没问题

**Comment by learningendless** [comment]
@daliansky 主板如果不支持nvme呢？因为这么做就是不想升级bios，bios升级应该也是没有官方的支持nvme的bios，所以就像通过这个方式绕过去，不知道是否可行。

**Comment by W-MS** [comment]
不可行。
