### ISSUE TITLE
跪求Z7M-KP7S1 efi 

### ISSUE THREAD

**Issue by bugs1998** [daliansky/Hackintosh#35]
HASEE Z7-KP7D1 | 链接 |   | Clevo P65xHPHASEE Z7-KP7S1
-- | -- | -- | --
神舟战神 Z7-KP7GZ | 链接 | 链接 | Z7(m)-KP7/5(G)Z

都是没有Z7m kp7s1

**Comment by JokerHYC** [comment]
傻孩子 切分支啊

**Comment by hurricanny** [comment]
https://github.com/hurricanny/hasee-z7kp7s1-macos-10.13.6-1060
13.6 可以用集成显卡模式 可以用它装14.6但是没有声音

**Comment by bugs1998** [comment]
你这个也是z7啊我的是z7m，z7因该同方模具，z7m是老得蓝天模具

**Comment by bugs1998** [comment]
> https://github.com/hurricanny/hasee-z7kp7s1-macos-10.13.6-1060
> 13.6可以用集成显卡模式可以用它装14.6但是没有声音
你这个也是Z7啊我的是z7m，Z7因该同方模具，z7m是老得蓝天模具

**Comment by bugs1998** [comment]
> 傻孩子切分支啊
