### ISSUE TITLE
HP ENVY 15 as119tu，求增加此机型

### ISSUE THREAD

**Issue by ulpyuxa** [daliansky/Hackintosh#42]
请求增加HP ENVY 15 as119tu机型，配置与110tu差不多（CPU、显示屏）不一样。目前我正在使用此电脑，文末有我的联系方式。

------鲁大师 Build V5.15.16.1295------

电脑型号: HP ENVY Notebook 笔记本电脑
操作系统: Windows 10 Enterprise 64位

  处理器: 英特尔 Core i5-7200U @ 2.50GHz 双核
    主板: 惠普 81D1
    内存: 16 GB ( 金士顿 DDR4 2133MHz / 金士顿 DDR4 2400MHz )
  主硬盘: 三星 NVMe MZVLW512 ( 512 GB / 固态硬盘 )
    显卡: 英特尔 HD Graphics 620 ( 128 MB / 惠普 )
  显示器: 三星 SDC5958 ( 15.3 英寸  )
    声卡: Conexant SmartAudio HD @ 英特尔 High Definition Audio 控制器
    网卡: 英特尔 Dual Band Wireless-AC 7265

我的联系方式企鹅号：345063643

**Comment by daliansky** [comment]
我只是个搬运工，没有收集的机型请通过搜索或者其它方式获得。
