### ISSUE TITLE
希望添加红米笔记本redmibook的配置，谢谢

### ISSUE THREAD

**Issue by dbv** [daliansky/Hackintosh#66]

**Comment by hzl666123** [comment]
电脑型号	TIMI RedmiBook 14 笔记本电脑  (扫描时间：2019年09月07日)
操作系统	Windows 10 64位 ( DirectX 12 )
	
处理器	英特尔 Core i7-8565U @ 1.80GHz 四核
主板	TIMI TM1814 ( I/O - 9D84 for mobile 8th Gen Intel Core processor family )
内存	8 GB ( 三星 )
主硬盘	三星 MZNLN512HAJQ-00000 ( 512 GB / 固态硬盘 )
显卡	Nvidia GeForce MX250 ( 2 GB )
显示器	NCP004A ( 14 英寸  )
声卡	英特尔 英特尔智音技术音频控制器
网卡	博通 43224AG 802.11a/b/g/draft-n Wi-Fi Adapter / 苹果
-------------------------
配置信息如上，同求，小白搞了2周还是没能把显卡正确驱动，求大佬支持.... @dbv

**Comment by 1047730442** [comment]
同求，全网都没有

**Comment by daliansky** [comment]
没有你们就造一个呗，然后就提交到我这里让更多人受益。

**Comment by dbv** [comment]
已经造好。地址
https://github.com/dbv/redmibook_hackintsh_EFI
