### ISSUE TITLE
联想小新Pro 13有成功的吗

### ISSUE THREAD

**Issue by tujidelv** [daliansky/Hackintosh#93]
如题，标压锐龙版以及十代U机型的Pro
有黑成功的告知一下啊

**Comment by daliansky** [comment]
> 如题，标压锐龙版以及十代U机型的Pro
> 有黑成功的告知一下啊

小新有pro黑苹果群:欢迎加入小新pro 黑苹果，群聊号码：946132482

**Comment by M69W** [comment]
https://github.com/daliansky/XiaoXinPro-13-hackintosh
