### ISSUE TITLE
提交一个我 技嘉 B360m d2v i5-8400核显的EFI

### ISSUE THREAD

**Issue by Matchas-xiaobin** [daliansky/Hackintosh#97]
https://github.com/Matchas-xiaobin/EFI-B360m_d2v_dvi_uhd630
10.14.6-10.15.1都没问题，声卡是用的VoodooHDA驱动。其他的暂时没发现任何问题。用UHD630 核显 DVI 输出。

**Comment by daliansky** [comment]
已收录，建议在`README.md`中注明主板型号及其它配置信息，包括无线网卡等。

**Comment by Matchas-xiaobin** [comment]
好的
