### ISSUE TITLE
add：ThinkPad T530已基本正常

### ISSUE THREAD

**Issue by RealKiro** [daliansky/Hackintosh#99]
使用 `CLOVER` + `OC-little` 重新制作，现已基本都正常
https://github.com/RealKiro/Hackintosh/tree/master/ThinkPad%20T530
![image](https://user-images.githubusercontent.com/33367701/69406446-28638b80-0d3d-11ea-8dbf-df3dacf5b566.png)
⚠️自带的Intel无线网卡是无解的，不换网卡就使用有线，换网卡请提前制作白名单刷入BIOS食用

- 感谢提供的OC-little

**Comment by luozhili1999** [comment]
同T530 我用的是  https://github.com/mighildotcom/ThinkPad-T530-Hackintosh  但出现vga口没有输出的问题，，，

**Comment by RealKiro** [comment]
> 同T530 我用的是 https://github.com/mighildotcom/ThinkPad-T530-Hackintosh 但出现vga口没有输出的问题，，，

不清楚外接VGA的问题，但是对于台式机而言普遍反应VGA是无解的，既然有miniDP接口的话就用miniDP，或者你可以买个miniDP转接VGA接头
